services:
  db:
    image: postgres:14-alpine
    container_name: santex_db
    restart: always
    environment:
      POSTGRES_USER: santexUser
      POSTGRES_PASSWORD: santex
      POSTGRES_DB: myFootballDB
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: node:22-alpine
    container_name: node_app
    restart: always
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    env_file:
      - .env
    command:
      ['sh', '-c', 'npm install && npx prisma migrate deploy && npm run dev']

volumes:
  postgres_data:
